### ISSUE TITLE
Fix potential caching issue

### ISSUE THREAD

**Issue by idflood** [acusticdemon/gulp-sass-import-json#2]
The use case would be that there might be a watch task which recompile the sass once the json/sass files change. Now there is a basic cache which prevent any change to the json to be reflected. The current workaround is to stop gulp and restart it.

Possible solution:
- disable the cache completely
- add an option to disable the cache `{cache: false}`

The current behavior first made me think of a bug, it's only after checking the source code that I understood that it was cache related. I would vote for a complete cache removal since I don't think the small performance benefit is worth the potential issues.

**Comment by acusticdemon** [comment]
fixed in v1.0.2
