### ISSUE TITLE
Issues with import

### ISSUE THREAD

**Issue by brantdarilek** [acusticdemon/gulp-sass-import-json#3]
I'm having issues with whats being output.
```{
    "colors": {
        "error": "#f00",
        "success": "#0f0"
    },
    "medium": "12px"
}
```

When being imported the map returns as follows which errors out and is invalid.
```
$colors: (error: #f00, success: #0f0)
$medium: 12px
;
```

Here is the sass error.
`Invalid CSS after "$medium": expected selector or at-rule, was ": 12px"`

**Comment by jozerozman** [comment]
@brantdarilek I see you closed this, but did you manage to find a solution to this? I'm having the exact same problem :)
