### ISSUE TITLE
Error on Sass syntax

### ISSUE THREAD

**Issue by acespace90** [acusticdemon/gulp-sass-import-json#6]
I get this error when I compile SASS
`Error: Invalid CSS after "{": expected 1 selector or at-rule, was "{"`

**Comment by acusticdemon** [comment]
If you use scss you should add option isScss
`.pipe(sassImportJson({isScss: true}))`

**Comment by acespace90** [comment]
mmmh same error

**Comment by acespace90** [comment]
The problem seems to be inside my SCSS entry point.
I have a main.scss where I call other scss files.

The gulp task is this 
```
gulp.task('styles', function() {
  gulp.src(['src/sass/main.scss'])
    .pipe(sassGlob())
    .pipe(rename('main.css'))
    .pipe(sourcemaps.init())
    .pipe(sassImportJson({isScss: true}))
    .pipe(sass().on('error', sass.logError))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./src/assets/css'))
});
```

The plugin works if i put the exact path to file like this
```
gulp.task('styles', function() {
  gulp.src(['src/sass/path/to/specific/file.scss'])
    .pipe(sassGlob())
    .pipe(rename('main.css'))
    .pipe(sourcemaps.init())
    .pipe(sassImportJson({isScss: true}))
    .pipe(sass().on('error', sass.logError))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./src/assets/css'))
});
```

Hope to be clear :)

**Comment by fquirogam** [comment]
I'm getting error, in my case my gulp task is pretty simple:

`import * as gulp from 'gulp';

const path_to_scss = 'src/client/app/home/home.component.scss';

const sassImportJson = require('gulp-sass-import-json');

export = () => {
  return gulp.src(path_to_scss)
    .pipe(sassImportJson({isScss: true}))
};`

**Comment by acusticdemon** [comment]
What kind of errors did you have?

**Comment by fquirogam** [comment]
Error: Invalid CSS after "{": expected 1 selector or at-rule, was "{"

**Comment by acusticdemon** [comment]
Try please. I tested gulp sass compiling with sass and scss.
